export const SET_RESULTS = "SET_RESULTS";
export const RESET_RESULT = "RESET_RESULT";

export const SET_RECOMMENDATIONS = "SET_RECOMMENDATIONS";
export const RESET_RECOMMENDATIONS="RESET_RECOMMENDATIONS";
