export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const SET_QUESTIONS = "SET_QUESTIONS";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const RESET_QUESTIONS = "RESET_QUESTIONS";
export const RESET_QUESTION_COUNTER="RESET_QUESTION_COUNTER";

export const ADD_ANSWER = "ADD_ANSWER";
export const NONE_OF_THE_ABOVE = "NONE_OF_THE_ABOVE";
export const RESET_ANSWERS="RESET_ANSWERS";
export const ADD_ANSWERS = "ADD_ANSWERS";
