import {
	NEAR_STORE,
	ACCUNITY_SERVICES1,
	ACCUNITY_SERVICES2,
	ACCUNITY_SERVICES3,
	MOBICOMMERCE1,
	MOBICOMMERCE2,
	MAGICPIN,
	NEOGROWTH,
	MYBILLBOOK,
	SNAPBIZZ,
	OK_CREDIT,
	VYAPAR,
	PINNACLE,
	RAZORPAY,
	APNA_CO,
	SYROW,
	SMARTECH,
	GO_DIGIT,
	CARE,
	VAKIL_SEARCH,
	BRANDPULSE,
	DIGI_HEALTH,
	PAYU,
	SPACE_OF_JOY,
	PAGARBOOK,
	EASY_FILE_ITR,
	HYLO_BIZ,
	NEOCASH_INSTA,
	MEDIAQART,
	THE_ONLINE_TEAM_1,
	THE_ONLINE_TEAM_2,
	THE_ONLINE_TEAM_3,
	THE_ONLINE_TEAM_4,
	ESTARTUP_INDIA,
	INSTABILL,
	URBAN_CFO,
	MSWIPE,
	BLUE_OCKTOPUS,
	TERRAGO_LOGISTICS,
	PORTER,
	COVID_COVER
} from "./strings";

export const partnerMapping = [
	{
		name: "mobicommerce",
		partner: MOBICOMMERCE1,
		heading: "Sell Online",
	},
	{
		name: "near store",
		partner: NEAR_STORE,
		heading: "Sell Online",
	},
	{
		name: "accunity services",
		partner: ACCUNITY_SERVICES1,
		heading: "Sell Online",
	},
	{
		name: "snapbizz",
		partner: SNAPBIZZ,
		heading: "Sell Online",
	},
	{
		name: "the online team (tot)",
		partner: THE_ONLINE_TEAM_1,
		heading: "Sell Online",
	},
	{
		name: "neogrowth",
		partner: NEOGROWTH,
		heading: "Business Loans",
	},
	{
		name: "neocash insta",
		partner: NEOCASH_INSTA,
		heading: "Business Loans",
	},
	{
		name: "snapbizz",
		partner: SNAPBIZZ,
		heading: "Inventory Management",
	},
	{
		name: "instabill",
		partner: INSTABILL,
		heading: "Inventory Management",
	},
	{
		name: "my billbook",
		partner: MYBILLBOOK,
		heading: "Inventory Management",
	},
	{
		name: "mobicommerce",
		partner: MOBICOMMERCE2,
		heading: "Create Website or Mobile App",
	},
	{
		name: "accunity services",
		partner: ACCUNITY_SERVICES2,
		heading: "Create Website or Mobile App",
	},
	{
		name: "pinnacle management & utility services",
		partner: PINNACLE,
		heading: "Create Website or Mobile App",
	},
	{
		name: "the online team (tot)",
		partner: THE_ONLINE_TEAM_2,
		heading: "Create Website or Mobile App",
	},
	{
		name: "snapbizz",
		partner: SNAPBIZZ,
		heading: "Billing & Accounting",
	},
	{
		name: "accunity services",
		partner: ACCUNITY_SERVICES3,
		heading: "Billing & Accounting",
	},
	{
		name: "my billbook",
		partner: MYBILLBOOK,
		heading: "Billing & Accounting",
	},
	{
		name: "digihealth",
		partner: DIGI_HEALTH,
		heading: "Billing & Accounting",
	},
	{
		name: "instabill",
		partner: INSTABILL,
		heading: "Billing & Accounting",
	},
	{
		name: "vyapar",
		partner: VYAPAR,
		heading: "Billing & Accounting",
	},
	{
		name: "hylo biz",
		partner: HYLO_BIZ,
		heading: "Manage Payments",
	},
	{
		name: "mswipe",
		partner: MSWIPE,
		heading: "Manage Payments",
	},
	{
		name: "vakilsearch",
		partner: VAKIL_SEARCH,
		heading: "Tax Filing & Legal",
	},
	{
		name: "easy file itr",
		partner: EASY_FILE_ITR,
		heading: "Tax Filing & Legal",
	},
	{
		name: "e-startup india",
		partner: ESTARTUP_INDIA,
		heading: "Tax Filing & Legal",
	},
	{
		name: "urbancfo",
		partner: URBAN_CFO,
		heading: "Tax Filing & Legal",
	},
	{
		name: "accunity services",
		partner: ACCUNITY_SERVICES2,
		heading: "Social Media & Digital Marketing",
	},
	{
		name: "pinnacle management & utility services",
		partner: PINNACLE,
		heading: "Social Media & Digital Marketing",
	},
	{
		name: "the online team (tot)",
		partner: THE_ONLINE_TEAM_3,
		heading: "Social Media & Digital Marketing",
	},
	{
		name: "payu",
		partner: PAYU,
		heading: "Manage Payments",
	},
	{
		name: "apna co",
		partner: APNA_CO,
		heading: "Manage Staff",
	},
	{
		name: "pagarbook",
		partner: PAGARBOOK,
		heading: "Manage Staff",
	},
	{
		name: "syrow",
		partner: SYROW,
		heading: "Customer Loyalty & Promotions",
	},
	{
		name: "brandppulse marketing services pvt ltd",
		partner: BRANDPULSE,
		heading: "Customer Loyalty & Promotions",
	},
	{
		name: "smartech electronic systems",
		partner: SMARTECH,
		heading: "Customer Loyalty & Promotions",
	},
	{
		name: "accunity services",
		partner: ACCUNITY_SERVICES1,
		heading: "Customer Loyalty & Promotions",
	},
	{
		name: "blue ocktopus",
		partner: BLUE_OCKTOPUS,
		heading: "Customer Loyalty & Promotions",
	},
	{
		name: "care",
		partner: CARE,
		heading: "Insurance",
	},
	{
		name: "godigit",
		partner: GO_DIGIT,
		heading: "Insurance",
	},
	{
		name: "space of joy",
		partner: SPACE_OF_JOY,
		heading: "Business Decor",
	},
	{
		name: "mediaqart",
		partner: MEDIAQART,
		heading: "Social Media & Digital Marketing",
	},
	{
		name: "the online team (tot)",
		partner: THE_ONLINE_TEAM_4,
		heading: "Product Photoshoot",
	},
	{
		name: "terrago logistics",
		partner: TERRAGO_LOGISTICS,
		heading: "Delivery & Logistics",
	},
	{
		name: "porter",
		partner: PORTER,
		heading: "Delivery & Logistics"
	},
	{
		name: "covid cover",
		partner: COVID_COVER,
		heading: "Insurance"
	},
];
